# This workflow setups a python env to check the GitHub api and generate the stats image
# This image is then uploaded to GitHub page for the repo its in

name: Lightweight Github Stats

on:
  workflow_dispatch:
 
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check Github API and generate image
        id: run_script
        run: |
          python app/main.py ${{ github.actor }} ${{ secrets.api_key }}
          echo "::set-output name=data_image::${PWD}/data.png"
          echo "::set-output name=graph_image::${PWD}/graph.png"
          echo "::set-output name=stats_image::${PWD}/stats.png"

      - name: Upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: page-build
          path: |
            ${{ steps.run_script.outputs.data_image }}
            ${{ steps.run_script.outputs.graph_image }}
            ${{ steps.run_script.outputs.stats_image }}
            index.html
            favicon.ico
  

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: page-build
          path: .

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
